---
abstract: 'Jungle is a web spider framework to speed up crawler developments'
author:
  - 'Hernan Lopes (hernanlopes@gmail.com)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jungle
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  DateTime: 0
  Digest::SHA1: 0
  Encode: 0
  Encode::Guess: 0
  HTML::Entities: 0
  HTML::TreeBuilder::XPath: 0
  HTTP::Request::Common: 0
  IO::Socket::SSL: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Role: 0
  Mozilla::CA: 0
  Test::Simple: 0.44
  Text::CSV_XS: 0
  URI: 0
  WWW::Mechanize: 0
  XML::XPath: 0
version: 0.01
